### ISSUE TITLE
jasmine-jquery@<2 yanked

### ISSUE THREAD

**Issue by jbpros** [cucumber-ltd/angular-cucumber-pro-toc#1]
Yes, right. jasmine-jquery has been removed from NPM. It's now impossible to run any tests. I tried upgrading but it's not straightforward, karma complains about a call to an undefined `jasmine.addMatchers()` method.

It looks like it's a new trend on NPM to yank older versions of published packages. This Is Wrong™.

**Comment by mattwynne** [comment]
https://github.com/velesin/jasmine-jquery/issues/197 might be relevant

**Comment by mattwynne** [comment]
https://github.com/velesin/jasmine-jquery/issues/168 also relevant.
